/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Finals;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Gui_Login extends javax.swing.JFrame {

    public Gui_Login() {
        initComponents();
        setBounds(600, 400, 300, 350);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeluser = new javax.swing.JLabel();
        jTextFielduser = new javax.swing.JTextField();
        jLabelpass = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonlogin = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        jLabeluser.setText("Username:");
        getContentPane().add(jLabeluser);
        getContentPane().add(jTextFielduser);

        jLabelpass.setText("Password:");
        getContentPane().add(jLabelpass);
        getContentPane().add(jPasswordField);

        jButtonlogin.setText("Log In");
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlogin);

        jButtoncancel.setText("Cancel");
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
        String username = jTextFielduser.getText();
        String password = new String(jPasswordField.getPassword());
        
        InformationSaved(username,password);
        
        JOptionPane.showMessageDialog(this, "Account saved successfully", "Saved", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonloginActionPerformed

    private void InformationSaved(String username, String password){
        try{
            File file = new File("C:\\Users\\ADMIN\\Documents\\UserInfo.txt");
    
            BufferedWriter credits = new BufferedWriter(new FileWriter(file,true));
            credits.write("Username:" + username + ", password: "+ password);
            credits.newLine();
            credits.close();
    
    }catch (IOException e){
        JOptionPane.showMessageDialog(this, "Error Saving Account", "Error", JOptionPane.ERROR_MESSAGE);
    
        }  
    }
    
    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
        jTextFielduser.setText("");
        jPasswordField.setText("");
    }//GEN-LAST:event_jButtoncancelActionPerformed

    public static void main(String args[]) {
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JLabel jLabelpass;
    private javax.swing.JLabel jLabeluser;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFielduser;
    // End of variables declaration//GEN-END:variables
}
